window.STOXASTIK_DATA = {
  "updated": "2026-09-12 13:50",
  "source": "Stoxastik_ERP_Baza_Birlesmis.xlsx · 5_Saldo",
  "saldo": [
    {
      "Mal_Kodu": "XM.PLD.01.005",
      "Mal_Adi": "Polad lövhə 5 mm",
      "Sinif": "XM",
      "Vahid": "kg",
      "Serbest": 72.0,
      "Rezerv": 10,
      "Blok_Zay": 5.0,
      "Blok_QC": 0,
      "Cem": 87,
      "Min_stok": 50,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "XM.LTN.01.001",
      "Mal_Adi": "Latun çubuq",
      "Sinif": "XM",
      "Vahid": "kg",
      "Serbest": 31.5,
      "Rezerv": 5,
      "Blok_Zay": 2.5,
      "Blok_QC": 0,
      "Cem": 39,
      "Min_stok": 30,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "SM.QYN.01.001",
      "Mal_Adi": "Qaynaq elektrodu",
      "Sinif": "SM",
      "Vahid": "kg",
      "Serbest": 28.0,
      "Rezerv": 0,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 28,
      "Min_stok": 15,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "XM.ELK.01.001",
      "Mal_Adi": "PCB tip A1",
      "Sinif": "XM",
      "Vahid": "əd",
      "Serbest": 50.0,
      "Rezerv": 10,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 60,
      "Min_stok": 40,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "YF.CRK.01.200",
      "Mal_Adi": "Çərçivə yığması",
      "Sinif": "YF",
      "Vahid": "əd",
      "Serbest": 16.0,
      "Rezerv": 2,
      "Blok_Zay": 1.0,
      "Blok_QC": 0,
      "Cem": 19,
      "Min_stok": 5,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "YF.HDR.01.500",
      "Mal_Adi": "Hidravlik blok",
      "Sinif": "YF",
      "Vahid": "əd",
      "Serbest": 20.0,
      "Rezerv": 1,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 21,
      "Min_stok": 3,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "GD.LTN.01.001",
      "Mal_Adi": "Latun talas",
      "Sinif": "GD",
      "Vahid": "kg",
      "Serbest": 12.0,
      "Rezerv": 0,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 12,
      "Min_stok": 0,
      "Serbest_kifayet": "Kifayət"
    },
    {
      "Mal_Kodu": "QB.ETK.01.001",
      "Mal_Adi": "Etiket rulon",
      "Sinif": "QB",
      "Vahid": "əd",
      "Serbest": 100.0,
      "Rezerv": 0,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 100,
      "Min_stok": 500,
      "Serbest_kifayet": "Çatışmır"
    },
    {
      "Mal_Kodu": "SM.YAG.01.001",
      "Mal_Adi": "Soyuducu yağ",
      "Sinif": "SM",
      "Vahid": "l",
      "Serbest": 16.0,
      "Rezerv": 0,
      "Blok_Zay": 0.0,
      "Blok_QC": 0,
      "Cem": 16,
      "Min_stok": 5,
      "Serbest_kifayet": "Kifayət"
    }
  ]
};
